smartbugs/dataset/bad_randomness/random_number_generator.sol analyzed (1 contracts)
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'smartbugs/dataset/bad_randomness/random_number_generator.sol_vul_report.json'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at start (/sGuardPlus/src/index.js:64:30)
    at Object.<anonymous> (/sGuardPlus/src/index.js:110:16)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'smartbugs/dataset/bad_randomness/random_number_generator.sol_vul_report.json'
}
