{
  "totalTests": 103,
  "passingTests": 56,
  "failingTests": 47,
  "totalFiles": 49,
  "passingFiles": 5,
  "failingFiles": 44,
  "failedSanity": 0,
  "passedSanity": 51,
  "failedSanityTests": [],
  "passedResults": [
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/mapping_write_test.js",
      "contractFile": "access_control/mapping_write.sol",
      "state": "passed"
    },
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/wallet_02_refund_nosub_test.js",
      "contractFile": "access_control/wallet_02_refund_nosub.sol",
      "state": "passed"
    },
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/wallet_03_wrong_constructor_test.js",
      "contractFile": "access_control/wallet_03_wrong_constructor.sol",
      "state": "passed"
    },
    {
      "title": "exploit denial of service vulnerability",
      "file": "denial_of_service/dos_simple_test.js",
      "contractFile": "denial_of_service/dos_simple.sol",
      "state": "passed"
    },
    {
      "title": "front running vulnerability",
      "file": "front_running/odds_and_evens_test.js",
      "contractFile": "front_running/odds_and_evens.sol",
      "state": "passed"
    }
  ],
  "failedResults": [
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/mycontract_test.js",
      "contractFile": "access_control/mycontract.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0x0165878a594ca255338adfa4d48449f69242eb8f)\n    at <UnrecognizedContract>.<unknown> (0xa513e6e4b8f2a923d98304ec87f64353c4d5c853)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at Context.<anonymous> (test/access_control/mycontract_test.js:63:5)"
    },
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/phishable_test.js",
      "contractFile": "access_control/phishable.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0x8a791620dd6260079bf849dc5567adc3f2fdc318)\n    at <UnrecognizedContract>.<unknown> (0x610178da211fef7d417bc0e6fed39f05609ad788)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at Context.<anonymous> (test/access_control/phishable_test.js:72:5)"
    },
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/simple_suicide_test.js",
      "contractFile": "access_control/simple_suicide.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0x0dcd1bf9a1b36ce34237eeafef220932846bcd82)\n    at <UnrecognizedContract>.<unknown> (0x9a676e781a523b5d0c0e43731313a708cb607508)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/access_control/simple_suicide_test.js:42:5)"
    },
    {
      "title": "exploit access control vulnerability",
      "file": "access_control/wallet_04_confused_sign_test.js",
      "contractFile": "access_control/wallet_04_confused_sign.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x7a2088a1bfc9d81c55368ae168c2c02570cb814f)\n    at <UnrecognizedContract>.<unknown> (0x09635f643e140090a9a8dcd712ed6285858cebef)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/access_control/wallet_04_confused_sign_test.js:71:5)"
    },
    {
      "title": "exploit overflow vulnerability",
      "file": "arithmetic/integer_overflow_add_test.js",
      "contractFile": "arithmetic/integer_overflow_add.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0xe6e340d132b5f46d1e472debcd681b2abc16e57e)\n    at <UnrecognizedContract>.<unknown> (0xc3e53f4d16ae77db1c982e75a937b9f60fe63690)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/integer_overflow_add_test.js:40:5)"
    },
    {
      "title": "exploit overflow vulnerability",
      "file": "arithmetic/integer_overflow_mapping_sym_1_test.js",
      "contractFile": "arithmetic/integer_overflow_mapping_sym_1.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x9e545e3c0baab3e08cdfd552c960a1050f373042)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.init (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/integer_overflow_mapping_sym_1_test.js:72:5)"
    },
    {
      "title": "exploit underflow vulnerability",
      "file": "arithmetic/integer_overflow_minimal_test.js",
      "contractFile": "arithmetic/integer_overflow_minimal.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0xa82ff9afd8f496c3d6ac40e2a0f282e47488cfc9)\n    at <UnrecognizedContract>.<unknown> (0x1613beb3b2c4f22ee086b2b38c1476a3ce7f78e8)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/integer_overflow_minimal_test.js:42:5)"
    },
    {
      "title": "exploit overflow vulnerability",
      "file": "arithmetic/integer_overflow_mul_test.js",
      "contractFile": "arithmetic/integer_overflow_mul.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x95401dc811bb5740090279ba06cfa8fcf6113778)\n    at <UnrecognizedContract>.<unknown> (0x998abeb3e57409262ae5b751f60747921b33613e)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/integer_overflow_mul_test.js:40:5)"
    },
    {
      "title": "exploit underflow vulnerability",
      "file": "arithmetic/integer_overflow_multitx_onefunc_feasible_test.js",
      "contractFile": "arithmetic/integer_overflow_multitx_onefunc_feasible.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x4826533b4897376654bb4d4ad88b7fafd0c98528)\n    at <UnrecognizedContract>.<unknown> (0x99bba657f2bbc93c02d617f8ba121cb8fc104acf)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/integer_overflow_multitx_onefunc_feasible_test.js:41:5)"
    },
    {
      "title": "exploit overflow vulnerability",
      "file": "arithmetic/overflow_simple_add_test.js",
      "contractFile": "arithmetic/overflow_simple_add.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x8f86403a4de0bb5791fa46b8e795c547942fe4cf)\n    at <UnrecognizedContract>.<unknown> (0x9d4454b023096f34b160d6b654540c56a1f81688)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/overflow_simple_add_test.js:42:5)"
    },
    {
      "title": "exploit overflow add vulnerability",
      "file": "arithmetic/overflow_single_tx_test.js",
      "contractFile": "arithmetic/overflow_single_tx.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x809d550fca64d94bd9f66e60752a544199cfac3d)\n    at <UnrecognizedContract>.<unknown> (0x4c5859f0f772848b2d91f1d83e2fe57935348029)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attackOverflowAddToState (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/overflow_single_tx_test.js:57:5)"
    },
    {
      "title": "exploit overflow mul vulnerability",
      "file": "arithmetic/overflow_single_tx_test.js",
      "contractFile": "arithmetic/overflow_single_tx.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x809d550fca64d94bd9f66e60752a544199cfac3d)\n    at <UnrecognizedContract>.<unknown> (0x4c5859f0f772848b2d91f1d83e2fe57935348029)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attackOverflowMulToState (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/overflow_single_tx_test.js:64:5)"
    },
    {
      "title": "exploit underflow vulnerability",
      "file": "arithmetic/overflow_single_tx_test.js",
      "contractFile": "arithmetic/overflow_single_tx.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x809d550fca64d94bd9f66e60752a544199cfac3d)\n    at <UnrecognizedContract>.<unknown> (0x4c5859f0f772848b2d91f1d83e2fe57935348029)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attackUnderflowToState (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/overflow_single_tx_test.js:71:5)"
    },
    {
      "title": "exploit overflow vulnerability",
      "file": "arithmetic/timelock_test.js",
      "contractFile": "arithmetic/timelock.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x5f3f1dbd7b74c6b46e8c44f98792a1daf8d69154)\n    at <UnrecognizedContract>.<unknown> (0xb7278a61aa25c888815afc32ad3cc52ff24fe575)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/timelock_test.js:57:5)"
    },
    {
      "title": "exploit underflow vulnerability",
      "file": "arithmetic/token_test.js",
      "contractFile": "arithmetic/token.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0x2bdcc0de6be1f7d2ee689a0342d76f52e8efaba3)\n    at <UnrecognizedContract>.<unknown> (0x7969c5ed335650692bc04293b07f5bf2e7a673c0)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/token_test.js:48:5)"
    },
    {
      "title": "exploit buy overflow vulnerability line 23",
      "file": "arithmetic/tokensalechallenge_test.js",
      "contractFile": "arithmetic/tokensalechallenge.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0xfd471836031dc5108809d173a067e8486b9047a3)\n    at <UnrecognizedContract>.<unknown> (0xc351628eb244ec633d5f21fbd6621e1a683b1181)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack_buy (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/tokensalechallenge_test.js:49:5)"
    },
    {
      "title": "exploit the catch the ether vulnerability",
      "file": "arithmetic/tokensalechallenge_test.js",
      "contractFile": "arithmetic/tokensalechallenge.sol",
      "state": "failed",
      "error": "VM Exception while processing transaction: invalid opcode",
      "stack": "Error: VM Exception while processing transaction: invalid opcode\n    at <UnrecognizedContract>.<unknown> (0xfd471836031dc5108809d173a067e8486b9047a3)\n    at <UnrecognizedContract>.<unknown> (0xc351628eb244ec633d5f21fbd6621e1a683b1181)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack_complete (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/arithmetic/tokensalechallenge_test.js:60:5)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f_test.js",
      "contractFile": "reentrancy/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f_test.js:90:39)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x23a91059fdc9579a9fbd0edc5f2ea0bfdb70deb4_test.js",
      "contractFile": "reentrancy/0x23a91059fdc9579a9fbd0edc5f2ea0bfdb70deb4.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x23a91059fdc9579a9fbd0edc5f2ea0bfdb70deb4_test.js:89:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1_test.js",
      "contractFile": "reentrancy/0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1_test.js:91:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x4e73b32ed6c35f570686b89848e5f39f20ecc106_test.js",
      "contractFile": "reentrancy/0x4e73b32ed6c35f570686b89848e5f39f20ecc106.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x4e73b32ed6c35f570686b89848e5f39f20ecc106_test.js:91:39)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x561eac93c92360949ab1f1403323e6db345cbf31_test.js",
      "contractFile": "reentrancy/0x561eac93c92360949ab1f1403323e6db345cbf31.sol",
      "state": "failed",
      "error": "expected 8000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 8000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x561eac93c92360949ab1f1403323e6db345cbf31_test.js:87:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x7541b76cb60f4c60af330c208b0623b7f54bf615_test.js",
      "contractFile": "reentrancy/0x7541b76cb60f4c60af330c208b0623b7f54bf615.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x7541b76cb60f4c60af330c208b0623b7f54bf615_test.js:92:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x7a8721a9d64c74da899424c1b52acbf58ddc9782_test.js",
      "contractFile": "reentrancy/0x7a8721a9d64c74da899424c1b52acbf58ddc9782.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x7a8721a9d64c74da899424c1b52acbf58ddc9782_test.js:91:39)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3_test.js",
      "contractFile": "reentrancy/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3_test.js:90:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x8c7777c45481dba411450c228cb692ac3d550344_test.js",
      "contractFile": "reentrancy/0x8c7777c45481dba411450c228cb692ac3d550344.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x8c7777c45481dba411450c228cb692ac3d550344_test.js:92:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x93c32845fae42c83a70e5f06214c8433665c2ab5_test.js",
      "contractFile": "reentrancy/0x93c32845fae42c83a70e5f06214c8433665c2ab5.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x93c32845fae42c83a70e5f06214c8433665c2ab5_test.js:93:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x941d225236464a25eb18076df7da6a91d0f95e9e_test.js",
      "contractFile": "reentrancy/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x941d225236464a25eb18076df7da6a91d0f95e9e_test.js:91:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0x96edbe868531bd23a6c05e9d0c424ea64fb1b78b_test.js",
      "contractFile": "reentrancy/0x96edbe868531bd23a6c05e9d0c424ea64fb1b78b.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0x96edbe868531bd23a6c05e9d0c424ea64fb1b78b_test.js:87:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8_test.js",
      "contractFile": "reentrancy/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8.sol",
      "state": "failed",
      "error": "expected 9000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 9000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8_test.js:91:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xb5e1b1ee15c6fa0e48fce100125569d430f1bd12_test.js",
      "contractFile": "reentrancy/0xb5e1b1ee15c6fa0e48fce100125569d430f1bd12.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xb5e1b1ee15c6fa0e48fce100125569d430f1bd12_test.js:90:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xb93430ce38ac4a6bb47fb1fc085ea669353fd89e_test.js",
      "contractFile": "reentrancy/0xb93430ce38ac4a6bb47fb1fc085ea669353fd89e.sol",
      "state": "failed",
      "error": "expected 7000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 7000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xb93430ce38ac4a6bb47fb1fc085ea669353fd89e_test.js:89:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xbaf51e761510c1a11bf48dd87c0307ac8a8c8a4f_test.js",
      "contractFile": "reentrancy/0xbaf51e761510c1a11bf48dd87c0307ac8a8c8a4f.sol",
      "state": "failed",
      "error": "expected 9000000000000000000 to be below 4000000000000000000.",
      "stack": "AssertionError: expected 9000000000000000000 to be below 4000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xbaf51e761510c1a11bf48dd87c0307ac8a8c8a4f_test.js:89:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888_test.js",
      "contractFile": "reentrancy/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888_test.js:91:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xcead721ef5b11f1a7b530171aab69b16c5e66b6e_test.js",
      "contractFile": "reentrancy/0xcead721ef5b11f1a7b530171aab69b16c5e66b6e.sol",
      "state": "failed",
      "error": "expected 10000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 10000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xcead721ef5b11f1a7b530171aab69b16c5e66b6e_test.js:90:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/0xf015c35649c82f5467c9c74b7f28ee67665aad68_test.js",
      "contractFile": "reentrancy/0xf015c35649c82f5467c9c74b7f28ee67665aad68.sol",
      "state": "failed",
      "error": "expected 8000000000000000000 to be below 3000000000000000000.",
      "stack": "AssertionError: expected 8000000000000000000 to be below 3000000000000000000.\n    at Context.<anonymous> (test/reentrancy/0xf015c35649c82f5467c9c74b7f28ee67665aad68_test.js:90:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/etherstore_test.js",
      "contractFile": "reentrancy/etherstore.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0x01e21d7b8c39dc4c764c19b308bd8b14b1ba139e)\n    at <UnrecognizedContract>.<unknown> (0x3c1cb427d20f15563ada8c249e71db76d7183b6c)\n    at <UnrecognizedContract>.<unknown> (0x01e21d7b8c39dc4c764c19b308bd8b14b1ba139e)\n    at <UnrecognizedContract>.<unknown> (0x3c1cb427d20f15563ada8c249e71db76d7183b6c)\n    at <UnrecognizedContract>.<unknown> (0x01e21d7b8c39dc4c764c19b308bd8b14b1ba139e)\n    at <UnrecognizedContract>.<unknown> (0x3c1cb427d20f15563ada8c249e71db76d7183b6c)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/reentrancy/etherstore_test.js:73:5)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/reentrance_test.js",
      "contractFile": "reentrancy/reentrance.sol",
      "state": "failed",
      "error": "expected 9000000000000000000 to be below 5000000000000000000.",
      "stack": "AssertionError: expected 9000000000000000000 to be below 5000000000000000000.\n    at Context.<anonymous> (test/reentrancy/reentrance_test.js:80:33)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/reentrancy_bonus_test.js",
      "contractFile": "reentrancy/reentrancy_bonus.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0x512f7469bcc83089497506b5df64c6e246b39925)\n    at <UnrecognizedContract>.<unknown> (0x9fd16ea9e31233279975d99d5e8fc91dd214c7da)\n    at <UnrecognizedContract>.<unknown> (0x512f7469bcc83089497506b5df64c6e246b39925)\n    at <UnrecognizedContract>.<unknown> (0x9fd16ea9e31233279975d99d5e8fc91dd214c7da)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/reentrancy/reentrancy_bonus_test.js:64:5)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/reentrancy_dao_test.js",
      "contractFile": "reentrancy/reentrancy_dao.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0xe8f7d98be6722d42f29b50500b0e318ef2be4fc8)\n    at <UnrecognizedContract>.<unknown> (0xe38b6847e611e942e6c80ed89ae867f522402e80)\n    at <UnrecognizedContract>.<unknown> (0xe8f7d98be6722d42f29b50500b0e318ef2be4fc8)\n    at <UnrecognizedContract>.<unknown> (0xe38b6847e611e942e6c80ed89ae867f522402e80)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/reentrancy/reentrancy_dao_test.js:70:5)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/reentrancy_simple_test.js",
      "contractFile": "reentrancy/reentrancy_simple.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0x4593ed9cbe6003e687e5e77368534bb04b162503)\n    at <UnrecognizedContract>.<unknown> (0xcd7c00ac6dc51e8dcc773971ac9221cc582f3b1b)\n    at <UnrecognizedContract>.<unknown> (0x4593ed9cbe6003e687e5e77368534bb04b162503)\n    at <UnrecognizedContract>.<unknown> (0xcd7c00ac6dc51e8dcc773971ac9221cc582f3b1b)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/reentrancy/reentrancy_simple_test.js:72:5)"
    },
    {
      "title": "should successfully drain funds through reentrancy attack",
      "file": "reentrancy/simple_dao_test.js",
      "contractFile": "reentrancy/simple_dao.sol",
      "state": "failed",
      "error": "Transaction reverted without a reason string",
      "stack": "Error: Transaction reverted without a reason string\n    at <UnrecognizedContract>.<unknown> (0xdf46e54aaadc1d55198a4a8b4674d7a4c927097a)\n    at <UnrecognizedContract>.<unknown> (0xf5c4a909455c00b99a90d93b48736f3196db5621)\n    at <UnrecognizedContract>.<unknown> (0xdf46e54aaadc1d55198a4a8b4674d7a4c927097a)\n    at <UnrecognizedContract>.<unknown> (0xf5c4a909455c00b99a90d93b48736f3196db5621)\n    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:446:41)\n    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)\n    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)\n    at Proxy.attack (node_modules/ethers/src.ts/contract/contract.ts:352:16)\n    at Context.<anonymous> (test/reentrancy/simple_dao_test.js:82:5)"
    },
    {
      "title": "exploit unchecked low level call vulnerability",
      "file": "unchecked_low_level_calls/0x52d2e0f9b01101a59b38a3d05c80b7618aeed984_test.js",
      "contractFile": "unchecked_low_level_calls/0x52d2e0f9b01101a59b38a3d05c80b7618aeed984.sol",
      "state": "failed",
      "error": "Expected transaction NOT to be reverted",
      "stack": "AssertionError: Expected transaction NOT to be reverted\n    at Context.<anonymous> (test/unchecked_low_level_calls/0x52d2e0f9b01101a59b38a3d05c80b7618aeed984_test.js:49:5)"
    },
    {
      "title": "exploit unchecked low level call vulnerability",
      "file": "unchecked_low_level_calls/0xb11b2fed6c9354f7aa2f658d3b4d7b31d8a13b77_test.js",
      "contractFile": "unchecked_low_level_calls/0xb11b2fed6c9354f7aa2f658d3b4d7b31d8a13b77.sol",
      "state": "failed",
      "error": "Expected transaction NOT to be reverted",
      "stack": "AssertionError: Expected transaction NOT to be reverted\n    at Context.<anonymous> (test/unchecked_low_level_calls/0xb11b2fed6c9354f7aa2f658d3b4d7b31d8a13b77_test.js:69:5)"
    },
    {
      "title": "exploit unchecked low level call vulnerability",
      "file": "unchecked_low_level_calls/0xb7c5c5aa4d42967efe906e1b66cb8df9cebf04f7_test.js",
      "contractFile": "unchecked_low_level_calls/0xb7c5c5aa4d42967efe906e1b66cb8df9cebf04f7.sol",
      "state": "failed",
      "error": "Expected transaction NOT to be reverted, but it reverted with reason 'Ether transfer failed'",
      "stack": "AssertionError: Expected transaction NOT to be reverted, but it reverted with reason 'Ether transfer failed'\n    at Context.<anonymous> (test/unchecked_low_level_calls/0xb7c5c5aa4d42967efe906e1b66cb8df9cebf04f7_test.js:78:5)"
    },
    {
      "title": "exploit unchecked low level call vulnerability",
      "file": "unchecked_low_level_calls/0xbaa3de6504690efb064420d89e871c27065cdd52_test.js",
      "contractFile": "unchecked_low_level_calls/0xbaa3de6504690efb064420d89e871c27065cdd52.sol",
      "state": "failed",
      "error": "Expected transaction NOT to be reverted",
      "stack": "AssertionError: Expected transaction NOT to be reverted\n    at Context.<anonymous> (test/unchecked_low_level_calls/0xbaa3de6504690efb064420d89e871c27065cdd52_test.js:66:5)"
    },
    {
      "title": "exploit unchecked low level call vulnerability",
      "file": "unchecked_low_level_calls/0xbebbfe5b549f5db6e6c78ca97cac19d1fb03082c_test.js",
      "contractFile": "unchecked_low_level_calls/0xbebbfe5b549f5db6e6c78ca97cac19d1fb03082c.sol",
      "state": "failed",
      "error": "Expected transaction NOT to be reverted",
      "stack": "AssertionError: Expected transaction NOT to be reverted\n    at Context.<anonymous> (test/unchecked_low_level_calls/0xbebbfe5b549f5db6e6c78ca97cac19d1fb03082c_test.js:66:5)"
    }
  ]
}